
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Aug 26 06:34:07 CEST 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCREMENT = 20;
  public static final int CONST = 5;
  public static final int NOTEQUAL = 30;
  public static final int SEMI = 46;
  public static final int LPAREN = 37;
  public static final int GREATER = 33;
  public static final int CONTINUE = 4;
  public static final int LESS = 31;
  public static final int MINUS = 25;
  public static final int DECREMENT = 21;
  public static final int CHARACTER = 50;
  public static final int RPAREN = 38;
  public static final int AND = 35;
  public static final int NULLISHCO = 22;
  public static final int OR = 36;
  public static final int COMMA = 44;
  public static final int CLASS = 16;
  public static final int DIV = 27;
  public static final int GEQ = 34;
  public static final int PLUS = 24;
  public static final int ASSIGN = 23;
  public static final int IF = 6;
  public static final int THIS = 17;
  public static final int DOT = 43;
  public static final int BOOLEAN = 49;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int EQUAL = 29;
  public static final int SUPER = 18;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int NUMBER = 48;
  public static final int MOD = 28;
  public static final int IDENT = 47;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int COLON = 45;
  public static final int LBRACE = 39;
  public static final int ELSE = 7;
  public static final int LSQUARE = 41;
  public static final int ENUM = 14;
  public static final int READ = 11;
  public static final int RSQUARE = 42;
  public static final int WHILE = 9;
  public static final int RBRACE = 40;
  public static final int EXTENDS = 19;
  public static final int PROG = 2;
  public static final int LEQ = 32;
  public static final int PRINT = 10;
  public static final int DO = 8;
}

